version: '3.1'

services:

  postgres:
    environment:
      - POSTGRES_USER=asm3
      - POSTGRES_PASSWORD=asm3
      - POSTGRES_DB=asm
    image: postgres
    restart: always
    ports:
      - 5432:5432

  memcached:
    image: memcached
    ports:
      - 11211:11211

  asm:
    image: asm3
    links:
      - "postgres"
      - "memcached"
    ports:
      - 8080:80
    build:
      context: ../../
      dockerfile: scripts/docker/Dockerfile
    volumes:
      - ./asm3.conf.dev:/etc/asm3.conf
